development:
  dialect: mysql
  datasource: root:Sukmadjarna1!@tcp(localhost:3306)/bluebird_database?parseTime=true
  table: migrations
  dir: migrations/sqlite3
test:
  dialect: mysql
  datasource: root:pass@tcp(localhost:3306)/report
  dir: migrations